'use client'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SessionContextProvider, Session, SupabaseClient } from '@supabase/auth-helpers-react'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import AuthProvider from './components/AuthProvider'



// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
const queryClient = new QueryClient();

export default  function RootLayout({children,}: {
  children: React.ReactNode;
 
})

{

  // const supabase = createServerComponentClient({cookies});
  // const {
  //   data:{session},
  // } = await supabase.auth.getSession();


  return (
    <>

      <QueryClientProvider client={queryClient}>

        <html lang="en">
          <body >
<AuthProvider>
            {children}</AuthProvider>
            </body>
        </html></QueryClientProvider>
    </>
  )
}
